### ISSUE TITLE
[BUG] Deleted lists return after map change/server restart.

### ISSUE THREAD

**Issue by M-archand** [M-archand/SharpTimer-WallLists#1]
![20240608141502_1](https://github.com/M-archand/SharpTimer-WallLists/assets/13469995/9b25c060-8b0e-41dc-87f2-9bfa81dac0fd)

**Comment by M-archand** [comment]
Note to self: tried to fix a deserialization error that was popping up by defining colors explicitly. Got rid of that error but still didn't fix issue.  Updated TopList(s) references to PointsList as well, didn't fix.

**Comment by NordicGamerFE** [comment]
![image](https://github.com/user-attachments/assets/ef3e614e-fd8c-458c-9061-260a225e688d)
dont know if this supposedly has been fixed but i still have issues with this
